@extends('app')
@section('content')
<h1 style="text-align:center;"><strong>404 Not Found :(</strong></h1>
</br>
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>
@endsection